name: Buildar e Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configura o java
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Altere para a versão do Java que você está usando
          distribution: 'temurin'

      - name: Instalar o Java
        run: sudo apt-get install -y ant

      - name: Rodar o Ant
        run: ant dist

      - name: Upa o jar como artefato
        uses: actions/upload-artifact@v3
        with:
          name: calculadora-fat
          path: dist/calculadora-fat.jar
